// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb0EIp1RPAu4U5j2EqBoT_BDXWQ1lIX2I',
    appId: '1:9039114320:web:1c63c9f1c1c9ed7287e155',
    messagingSenderId: '9039114320',
    projectId: 'pharmas-f8951',
    authDomain: 'pharmas-f8951.firebaseapp.com',
    databaseURL: 'https://pharmas-f8951-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pharmas-f8951.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpExSt9C7I086Flu6ZjmA3owLLMTQFsg',
    appId: '1:9039114320:android:7e1f30698699fbed87e155',
    messagingSenderId: '9039114320',
    projectId: 'pharmas-f8951',
    databaseURL: 'https://pharmas-f8951-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pharmas-f8951.firebasestorage.app',
  );
}
